[package]
name = "wiktionary_dump2"
version = "0.1.0"
authors = ["Erutuon <5840197+Erutuon@users.noreply.github.com>"]
edition = "2018"

[dependencies]
parse_mediawiki_dump = {path = "../parse_mediawiki_dump"}
parse_wiki_text = {path = "../parse_wiki_text"}
structopt = "0.2.18"