[package]
name = "parse_wiki_text_ext"
version = "0.1.0"
authors = ["gbertilson <5840197+Erutuon@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parse_wiki_text = "0.1.5"